/*******************************************************************************
* FILENAME: project.h
* 
* PSoC Creator  3.2
*
* DESCRIPTION:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2015 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "A_B.h"
#include "OutMux.h"
#include "C_D.h"
#include "E_F.h"
#include "G_A.h"
#include "Control_Reg.h"
#include "Audio_out_aliases.h"
#include "Audio_out.h"
#include "Status_Reg.h"
#include "ADC.h"
#include "A_Key_aliases.h"
#include "A_Key.h"
#include "B_Key_aliases.h"
#include "B_Key.h"
#include "C_Key_aliases.h"
#include "C_Key.h"
#include "D_Key_aliases.h"
#include "D_Key.h"
#include "E_Key_aliases.h"
#include "E_Key.h"
#include "F_Key_aliases.h"
#include "F_Key.h"
#include "G_Key_aliases.h"
#include "G_Key.h"
#include "A2_Key_aliases.h"
#include "A2_Key.h"
#include "Pot_Vals.h"
#include "Pot_A_aliases.h"
#include "Pot_A.h"
#include "Pot_B_aliases.h"
#include "Pot_B.h"
#include "Clock.h"
#include "A0_aliases.h"
#include "A0.h"
#include "A1_aliases.h"
#include "A1.h"
#include "Tremolo.h"
#include "Amp.h"
#include "A_B_DacClk.h"
#include "A_B_Wave1_DMA_dma.h"
#include "A_B_Wave2_DMA_dma.h"
#include "A_B_VDAC8.h"
#include "C_D_DacClk.h"
#include "C_D_Wave1_DMA_dma.h"
#include "C_D_Wave2_DMA_dma.h"
#include "C_D_VDAC8.h"
#include "E_F_DacClk.h"
#include "E_F_Wave1_DMA_dma.h"
#include "E_F_Wave2_DMA_dma.h"
#include "E_F_VDAC8.h"
#include "G_A_DacClk.h"
#include "G_A_Wave1_DMA_dma.h"
#include "G_A_Wave2_DMA_dma.h"
#include "G_A_VDAC8.h"
#include "ADC_IRQ.h"
#include "ADC_theACLK.h"
#include "ADC_Bypass_aliases.h"
#include "ADC_Bypass.h"
#include "core_cm3_psoc5.h"
#include "core_cm3.h"
#include "CyDmac.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cypins.h"
#include "cyPm.h"
#include "CySpc.h"
#include "cytypes.h"
#include "core_cmFunc.h"
#include "core_cmInstr.h"

/*[]*/

